export enum SolicitacaoCategoria {
    SUPORTE_TECNICO = 'SUPORTE_TECNICO',
    COBRANCA = 'COBRANCA',
    VIDA_ACADEMICA = 'VIDA_ACADEMICA',
    ATENDIMENTO = 'ATENDIMENTO',
    NAO_IDENTIFICADO = 'NAO_IDENTIFICADO',
}